/*
* generated by Xtext
*/
package org.argouml.xtuml.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class OALTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
